algoritmo "Num_Maior"
var
   N1, N2: Inteiro
inicio
      Escreva ("Digite um número: ")
      Leia (N1)
      Escreva ("Digite outro número: ")
      Leia (N2)
      Se (N1 > N2) entao
         Escreval ("O primeiro valor é maior. ")
      Senao
           Se (N2 > N1) entao
              Escreval ("O segundo valor é maior. ")
           Senao
                Escreval ("Não exite valor maior, os dois são iguais. ")
           FimSe
      FimSe
fimalgoritmo
